In [1]:
import requests
import pandas as pd
from datetime import datetime, timedelta

# Initialiser les DataFrames
df_programmes = pd.DataFrame()
df_reunions = pd.DataFrame()
df_courses = pd.DataFrame()
df_participations = pd.DataFrame()

id_course = 0
id_reunion = 0
id_participation = 0

# Date du premier enregistrement 19-02-2013
# id_programme = 19022013

# Date du premier enregistrement 19-02-2013
start_date = datetime.strptime("19022013", "%d%m%Y")
end_date = datetime.strptime("01032013", "%d%m%Y")
# end_date = datetime.now()

current_date = start_date

while current_date <= end_date:
    id_programme = current_date.strftime("%d%m%Y")

    # URL avec la date de début
    url = f"https://offline.turfinfo.api.pmu.fr/rest/client/7/programme/{id_programme}"

    # Récupération du Json
    response = requests.get(url)

    if response.status_code == 200:
        json_data = response.json()

        #------------------------------------------------------------------- Construction de la table programme -------------------------------------------------------------------
        # Extraire les informations du programme
        date_programme_timestamp = json_data["programme"]["date"] // 1000
        date_programme = datetime.fromtimestamp(date_programme_timestamp).date()

        # Format personnalisé de la date en français
        date_programme_fr = date_programme.strftime("%Y-%m-%d")

        # Afficher les informations du programme
        # print(f"Id du programme : {id_programme} | Date du programme : {date_programme_fr}")
        df_programmes = pd.concat([df_programmes, pd.DataFrame([{"id_programme": id_programme, "date_programme": date_programme_fr}])], ignore_index=True)
        #------------------------------------------------------------------- Construction de la table programme -------------------------------------------------------------------

        #------------------------------------------------------------------- Construction de la table reunions --------------------------------------------------------------------

        for reunion in json_data["programme"]["reunions"]:
            # id_reunion est date + numero de la reunion exemple 19022013R1
            id_reunion += 1

            discipline_mere = ', '.join(reunion.get("disciplinesMere", []))
            specialites = reunion.get("specialites", [])

            # Assurez-vous d'avoir suffisamment d'éléments, sinon remplissez avec None
            specialites_padded = specialites + [None] * (4 - len(specialites))

            reunion_data = {
                "id_reunion": id_reunion,
                "id_programme": id_programme,
                "num_officiel": reunion.get("numOfficiel"),
                "nature": reunion.get("nature"),
                "code_hippodrome": reunion.get("hippodrome", {}).get("code"),
                "libelle_court_hippodrome": reunion.get("hippodrome", {}).get("libelleCourt"),
                "libelle_long_hippodrome": reunion.get("hippodrome", {}).get("libelleLong"),
                "code_pays": reunion["pays"].get("code"),
                "libelle_pays": reunion["pays"].get("libelle"),
                "audience": reunion.get("audience"),
                "statut": reunion.get("statut"),
                "disciplines_mere": discipline_mere,
                "specialite_1": specialites_padded[0],
                "specialite_2": specialites_padded[1],
                "specialite_3": specialites_padded[2],
                "specialite_4": specialites_padded[3],
                "meteo_nebulosite_code": reunion.get("meteo", {}).get("nebulositeCode"),
                "meteo_nebulosite_Libelle_Court": reunion.get("meteo", {}).get("nebulositeLibelleCourt"),
                "meteo_nebulosite_Libelle_Long": reunion.get("meteo", {}).get("nebulositeLibelleLong"),
                "meteo_temperature": reunion.get("meteo", {}).get("temperature"),
                "meteo_force_vent": reunion.get("meteo", {}).get("forceVent"),
                "meteo_direction_vent": reunion.get("meteo", {}).get("directionVent")
            }

            df_reunions = pd.concat([df_reunions, pd.DataFrame([reunion_data])], ignore_index=True)
            #------------------------------------------------------------------- Construction de la table reunions --------------------------------------------------------------------




            #------------------------------------------------------------------- Construction de la table courses --------------------------------------------------------------------
            num_reunion = reunion_data['num_officiel']
            url_courses = f"https://offline.turfinfo.api.pmu.fr/rest/client/7/programme/{id_programme}/R{num_reunion}"

            # Récupération du Json
            response_courses = requests.get(url_courses)

            if response_courses.status_code == 200:
                json_data_courses = response_courses.json()
            

                for course in json_data_courses["courses"]:
                    id_course += 1
                    heureDepart_timestamp = course.get("heureDepart", 0) // 1000

                    # Gérer les timestamps négatifs
                    if heureDepart_timestamp < 0:
                        heureDepart = None
                    else:
                        heureDepart = datetime.fromtimestamp(heureDepart_timestamp).time()

                    # Convertir dureeCourse de millisecondes à un format lisible
                    duree_course_ms = course.get("dureeCourse", 0)
                    duree_course_minutes, duree_course_seconds = divmod(duree_course_ms // 1000, 60)
                    duree_course_formatted = f"{duree_course_minutes}m {duree_course_seconds}s"

                    # Extraction des incidents
                    incidents_list = course.get("incidents", [])
                    incidents_type = [incident.get("type") for incident in incidents_list] if isinstance(incidents_list, list) else []
                    incidents_participants = [incident.get("numeroParticipants") for incident in incidents_list] if isinstance(incidents_list, list) else []

                    # Conversion des listes en chaînes de caractères
                    incidents_type_str = ' | '.join(incidents_type)
                    incidents_participants_str = ' | '.join([', '.join(map(str, participants)) for participants in incidents_participants])

                    specialites = reunion.get("specialites", [None, None])  # Deux spécialités ou None
                    specialite_1 = specialites[0] if len(specialites) > 0 else None
                    specialite_2 = specialites[1] if len(specialites) > 1 else None

                    # Récupération des ordres d'arrivée
                    ordre_arrivee = course.get("ordreArrivee", [])
                    ordre_arrivee_padded = [ordre[0] if isinstance(ordre, list) else ordre for ordre in (ordre_arrivee + [None] * (5 - len(ordre_arrivee)))]

                    course_data = {
                        "id_course": id_course,
                        "id_reunion": id_reunion,
                        "libelle": course.get("libelle"),
                        "libelle_court": course.get("libelleCourt"),
                        "heure_depart": heureDepart,
                        "parcours": course.get("parcours"),
                        "distance": course.get("distance"),
                        "distance_unit": course.get("distanceUnit"),
                        "corde": course.get("corde"),
                        "discipline": course.get("discipline"),
                        "specialite_1": specialite_1,
                        "specialite_2": specialite_2,
                        "condition_sexe": course.get("conditionSexe"),
                        "conditions": course.get("conditions"),
                        "statut": course.get("statut"),
                        "categorie_statut": course.get("categorieStatut"),
                        "duree_course": course.get("dureeCourse"),
                        "duree_course_en_minute":duree_course_formatted,
                        "montant_prix": course.get("montantPrix"),
                        "grand_prix_national_trot": course.get("grandPrixNationalTrot"),
                        "nombre_declares_partants": course.get("nombreDeclaresPartants"),
                        "montant_total_offert": course.get("montantTotalOffert"),
                        "premier": ordre_arrivee_padded[0],
                        "montant_offert_1er": course.get("montantOffert1er"),
                        "deuxieme": ordre_arrivee_padded[1],
                        "montant_offert_2eme": course.get("montantOffert2eme"),
                        "troisieme": ordre_arrivee_padded[2],
                        "montant_offert_3eme": course.get("montantOffert3eme"),
                        "quatrieme": ordre_arrivee_padded[3],
                        "montant_offert_4eme": course.get("montantOffert4eme"),
                        "cinquieme": ordre_arrivee_padded[4],
                        "montant_offert_5eme": course.get("montantOffert5eme"),
                        "incidents_type": incidents_type_str,
                        "incidents_participants": incidents_participants_str,
                    }
                    df_courses = pd.concat([df_courses, pd.DataFrame([course_data])], ignore_index=True)
                    #------------------------------------------------------------------- Construction de la table courses --------------------------------------------------------------------


                    #------------------------------------------------------------------- Construction de la table participations -------------------------------------------------------------
                    num_course = course.get("numOrdre")
                    url_participants = f"https://offline.turfinfo.api.pmu.fr/rest/client/7/programme/{id_programme}/R{num_reunion}/C{num_course}/participants"

                    # Récupération du Json
                    response_participants = requests.get(url_participants)

                    if response_participants.status_code == 200:
                        json_data_participants = response_participants.json()

                        for participant in json_data_participants["participants"]:
                            id_participation += 1

                            # Convertir dureeCourse de millisecondes à un format lisible
                            temps_obtenu_ms = participant.get("tempsObtenu", 0)
                            temps_obtenu_minutes, temps_obtenu_seconds = divmod(temps_obtenu_ms // 1000, 60)
                            temps_obtenu_formatted = f"{temps_obtenu_minutes}m {temps_obtenu_seconds}s"

                            participation_data = {
                                "id_participation": id_participation,
                                "id_course": id_course,
                                "nom": participant.get("nom"),
                                "numero_cheval": participant.get("numPmu"),
                                "age": participant.get("age"),
                                "sexe": participant.get("sexe"),
                                "race": participant.get("race"),
                                "statut": participant.get("statut"),
                                "proprietaire": participant.get("proprietaire"),
                                "entraineur": participant.get("entraineur"),
                                "driver": participant.get("driver"),
                                "driverChange": participant.get("driverChange"),
                                "code_robe": participant.get("robe", {}).get("code"),
                                "libelleCourt_robe": participant.get("robe", {}).get("libelleCourt"),
                                "libelleLong_robe": participant.get("robe", {}).get("libelleLong"),
                                "nombre_courses": participant.get("nombreCourses"),
                                "nombre_victoires": participant.get("nombreVictoires"),
                                "nombre_places": participant.get("nombrePlaces"),
                                "nom_pere": participant.get("nomPere"),
                                "nom_mere": participant.get("nomMere"),
                                "ordre_arrivee": participant.get("ordreArrivee"),
                                "jument_pleine": participant.get("jumentPleine"),
                                "engagement": participant.get("engagement"),
                                "supplement": participant.get("supplement"),
                                "handicap_distance": participant.get("handicapDistance"),
                                "poids_condition_monte_change": participant.get("poidsConditionMonteChange"),
                                "temps_obtenu": participant.get("tempsObtenu"),
                                "temps_obtenu_en_minute": temps_obtenu_formatted,
                                "reduction_kilometrique": participant.get("reductionKilometrique"),
                                "allure": participant.get("allure"),
                            }
                            df_participations = pd.concat([df_participations, pd.DataFrame([participation_data])], ignore_index=True)


                    #------------------------------------------------------------------- Construction de la table participations -------------------------------------------------------------

    else:
        print(f"Échec de la récupération des données, code de statut : {response.status_code}")

    # Passer à la date suivante
    current_date += timedelta(days=1)

In [2]:
df_programmes

   id_programme date_programme
0      19022013     2013-02-19
1      20022013     2013-02-20
2      21022013     2013-02-21
3      22022013     2013-02-22
4      23022013     2013-02-23
5      24022013     2013-02-24
6      25022013     2013-02-25
7      26022013     2013-02-26
8      27022013     2013-02-27
9      28022013     2013-02-28
10     01032013     2013-03-01

In [3]:
print(df_reunions)

    id_reunion id_programme  num_officiel        nature code_hippodrome  \
0            1     19022013             1        DIURNE             VIN
1            2     19022013             4      NOCTURNE             CAG
2            3     19022013             5  SEMINOCTURNE             HWM
3            4     19022013            10        DIURNE             LIG
4            5     20022013             3  SEMINOCTURNE             ENG
5            6     20022013             5        DIURNE             XKD
6            7     20022013             6        DIURNE            None
7            8     21022013             1        DIURNE             VIN
8            9     21022013             2        DIURNE             BOR
9           10     21022013             3  SEMINOCTURNE             GAL
10          11     21022013             4        DIURNE            None
11          12     21022013             5  SEMINOCTURNE             DUB
12          13     22022013             1        DIURNE             ENG
13          14     22022013             2        DIURNE             VIL
14          15     22022013             3  SEMINOCTURNE             CRO
15          16     22022013             4      NOCTURNE             CAG
16          17     22022013             5        DIURNE            None
17          18     22022013             6        DIURNE             SIN
18          19     22022013             7      NOCTURNE             SON
19          20     23022013             1        DIURNE             CAG
20          21     23022013             2        DIURNE             ENG
21          22     23022013             3  SEMINOCTURNE             CEP
22          23     23022013             4  SEMINOCTURNE            None
23          24     23022013             6        DIURNE             KEM
24          25     24022013             1        DIURNE             VIN
25          26     24022013             2        DIURNE             PET
26          27     24022013             3        DIURNE             ANG
27          28     24022013             4        DIURNE             XGD
28          29     24022013             6        DIURNE             NIM
29          30     24022013             7        DIURNE             AMI
30          31     24022013             9        DIURNE             PAR
31          32     24022013            10        DIURNE             GRA
32          33     24022013            11        DIURNE             LAV
33          34     25022013             1        DIURNE             BOR
34          35     25022013             3  SEMINOCTURNE             ENG
35          36     25022013             5        DIURNE             CHT
36          37     26022013             2        DIURNE             LAV
37          38     26022013             3  SEMINOCTURNE             PON
38          39     26022013             4      NOCTURNE             CAG
39          40     26022013             5  SEMINOCTURNE             XTD
40          41     27022013             1        DIURNE             ENG
41          42     27022013             2        DIURNE             CEP
42          43     27022013             3  SEMINOCTURNE             VIL
43          44     28022013             1        DIURNE             VIN
44          45     28022013             3  SEMINOCTURNE             CRO
45          46     28022013             4        DIURNE            None
46          47     28022013             5  SEMINOCTURNE             DUB
47          48     01032013             1        DIURNE             DEA
48          49     01032013             2        DIURNE             PCH
49          50     01032013             3      NOCTURNE             CAG
50          51     01032013             4        DIURNE            None
51          52     01032013             5        DIURNE             SIN
52          53     01032013             6  SEMINOCTURNE             SON
53          54     01032013             8  SEMINOCTURNE             VIL

   libelle_court_hippodrome              libelle_long_hippodrome code_pays  \
0                 VINCENNES        HIPPODROME DE PARIS-VINCENNES       FRA
1                CAGNES/MER             HIPPODROME DE CAGNES/MER       FRA
2              MONS (GHLIN)         HIPPODROME DE MONS  BELGIQUE       BEL
3                 LIGNIERES              HIPPODROME DE LIGNIERES       FRA
4                   ENGHIEN           HIPPODROME D'ENGHIEN SOISY       FRA
5                KENILWORTH      HIPPODROME DE KENILWORTH AF SUD       ZAF
6                      None                                 None       AUS
7                 VINCENNES        HIPPODROME DE PARIS-VINCENNES       FRA
8                    BORELY       HIPPODROME DE MARSEILLE BORELY       FRA
9             SAINT GALMIER          HIPPODROME DE SAINT GALMIER       FRA
10                     None                                 None       ZAF
11           MEYDAN (E.A.U)                HIPPODROME MEYDAN EAU       ARE
12                  ENGHIEN           HIPPODROME D'ENGHIEN SOISY       FRA
13             LYON LA SOIE           HIPPODROME DE LYON LA SOIE       FRA
14        LE CROISE LAROCHE         HIPPODROME DU CROISE LAROCHE       FRA
15               CAGNES/MER             HIPPODROME DE CAGNES/MER       FRA
16                     None                                 None       ZAF
17                SINGAPOUR              HIPPODROME DE SINGAPOUR       SGP
18                SON PARDO        HIPPODROME DE SON PARDO PALMA       ESP
19               CAGNES/MER             HIPPODROME DE CAGNES/MER       FRA
20                  ENGHIEN           HIPPODROME D'ENGHIEN SOISY       FRA
21               LA CEPIERE    HIPPODROME DE TOULOUSE LA CEPIERE       FRA
22                     None                                 None       URY
23             KEMPTON PARK       HIPPODROME DE KEMPTON PARK  GB       GBR
24                VINCENNES        HIPPODROME DE PARIS-VINCENNES       FRA
25                   NANTES                 HIPPODROME DE NANTES       FRA
26                   ANGERS         HIPPODROME D'ANGERS EVENTARD       FRA
27                GREYVILLE    HIPPODROME DE GREYVILLE AFRDU SUD       ZAF
28                    NIMES                  HIPPODROME DE NIMES       FRA
29                   AMIENS                  HIPPODROME D'AMIENS       FRA
30          PARAY LE MONIAL        HIPPODROME DE PARAY LE MONIAL       FRA
31                 GRAIGNES               HIPPODROME DE GRAIGNES       FRA
32                    LAVAL                  HIPPODROME DE LAVAL       FRA
33                   BORELY       HIPPODROME DE MARSEILLE BORELY       FRA
34                  ENGHIEN           HIPPODROME D'ENGHIEN SOISY       FRA
35     CHATILLON/CHALARONNE  HIPPODROME CHATILLON SUR CHALARONNE       FRA
36                    LAVAL                  HIPPODROME DE LAVAL       FRA
37           PONT DE VIVAUX  HIPPODROME MARSEILLE PONT DE VIVAUX       FRA
38               CAGNES/MER             HIPPODROME DE CAGNES/MER       FRA
39              TURFFONTEIN     HIPPODROME DE TURFFONTEIN AF SUD       ZAF
40                  ENGHIEN           HIPPODROME D'ENGHIEN SOISY       FRA
41               LA CEPIERE    HIPPODROME DE TOULOUSE LA CEPIERE       FRA
42             LYON LA SOIE           HIPPODROME DE LYON LA SOIE       FRA
43                VINCENNES        HIPPODROME DE PARIS-VINCENNES       FRA
44        LE CROISE LAROCHE         HIPPODROME DU CROISE LAROCHE       FRA
45                     None                                 None       ZAF
46           MEYDAN (E.A.U)                HIPPODROME MEYDAN EAU       ARE
47                DEAUVILLE              HIPPODROME DE DEAUVILLE       FRA
48              PONTCHATEAU            HIPPODROME DE PONTCHATEAU       FRA
49               CAGNES/MER             HIPPODROME DE CAGNES/MER       FRA
50                     None                                 None       ZAF
51                SINGAPOUR              HIPPODROME DE SINGAPOUR       SGP
52                SON PARDO        HIPPODROME DE SON PARDO PALMA       ESP
53             LYON LA SOIE           HIPPODROME DE LYON LA SOIE       FRA

           libelle_pays  audience  ... specialite_1 specialite_2 specialite_3  \
0                FRANCE  NATIONAL  ...  TROT_ATTELE   TROT_MONTE         None
1                FRANCE  NATIONAL  ...  TROT_ATTELE         None         None
2              Belgique  NATIONAL  ...  TROT_ATTELE         None         None
3                FRANCE  REGIONAL  ...  TROT_ATTELE         None         None
4                FRANCE  NATIONAL  ...  TROT_ATTELE   TROT_MONTE         None
5        Afrique du Sud  NATIONAL  ...         PLAT         None         None
6             Australie  NATIONAL  ...         PLAT         None         None
7                FRANCE  NATIONAL  ...   TROT_MONTE  TROT_ATTELE         None
8                FRANCE  NATIONAL  ...     OBSTACLE         PLAT         None
9                FRANCE  NATIONAL  ...   TROT_MONTE  TROT_ATTELE         None
10       Afrique du Sud  NATIONAL  ...         PLAT         None         None
11  Emirats arabes unis  NATIONAL  ...         PLAT         None         None
12               FRANCE  NATIONAL  ...  TROT_ATTELE   TROT_MONTE         None
13               FRANCE  NATIONAL  ...         PLAT         None         None
14               FRANCE  NATIONAL  ...  TROT_ATTELE   TROT_MONTE         None
15               FRANCE  NATIONAL  ...  TROT_ATTELE         None         None
16       Afrique du Sud  NATIONAL  ...         PLAT         None         None
17            Singapour  NATIONAL  ...         PLAT         None         None
18              Espagne  NATIONAL  ...  TROT_ATTELE         None         None
19               FRANCE  NATIONAL  ...         PLAT         None         None
20               FRANCE  NATIONAL  ...  TROT_ATTELE   TROT_MONTE         None
21               FRANCE  NATIONAL  ...  TROT_ATTELE   TROT_MONTE         None
22              Uruguay  NATIONAL  ...         PLAT         None         None
23          Royaume-Uni  NATIONAL  ...     OBSTACLE         None         None
24               FRANCE  NATIONAL  ...  TROT_ATTELE   TROT_MONTE         None
25               FRANCE  NATIONAL  ...  TROT_ATTELE   TROT_MONTE         None
26               FRANCE  NATIONAL  ...     OBSTACLE         None         None
27       Afrique du Sud  NATIONAL  ...         PLAT         None         None
28               FRANCE  NATIONAL  ...     OBSTACLE         PLAT         None
29               FRANCE  REGIONAL  ...   TROT_MONTE  TROT_ATTELE         None
30               FRANCE  REGIONAL  ...  TROT_ATTELE         None         None
31               FRANCE     LOCAL  ...  TROT_ATTELE   TROT_MONTE         None
32               FRANCE     LOCAL  ...  TROT_ATTELE   TROT_MONTE         None
33               FRANCE  NATIONAL  ...         PLAT     OBSTACLE         None
34               FRANCE  NATIONAL  ...  TROT_ATTELE   TROT_MONTE         None
35               FRANCE  NATIONAL  ...  TROT_ATTELE         None         None
36               FRANCE  NATIONAL  ...  TROT_ATTELE   TROT_MONTE         None
37               FRANCE  NATIONAL  ...         PLAT         None         None
38               FRANCE  NATIONAL  ...  TROT_ATTELE   TROT_MONTE         None
39       Afrique du Sud  NATIONAL  ...         PLAT         None         None
40               FRANCE  NATIONAL  ...  TROT_ATTELE   TROT_MONTE         None
41               FRANCE  NATIONAL  ...     OBSTACLE         PLAT         None
42               FRANCE  NATIONAL  ...         PLAT         None         None
43               FRANCE  NATIONAL  ...  TROT_ATTELE   TROT_MONTE         None
44               FRANCE  NATIONAL  ...  TROT_ATTELE   TROT_MONTE         None
45       Afrique du Sud  NATIONAL  ...         PLAT         None         None
46  Emirats arabes unis  NATIONAL  ...         PLAT         None         None
47               FRANCE  NATIONAL  ...         PLAT         None         None
48               FRANCE  NATIONAL  ...  TROT_ATTELE   TROT_MONTE         None
49               FRANCE  NATIONAL  ...  TROT_ATTELE         None         None
50       Afrique du Sud  NATIONAL  ...         PLAT         None         None
51            Singapour  NATIONAL  ...         PLAT         None         None
52              Espagne  NATIONAL  ...  TROT_ATTELE         None         None
53               FRANCE  REGIONAL  ...  TROT_ATTELE   TROT_MONTE         None

   specialite_4 meteo_nebulosite_code meteo_nebulosite_Libelle_Court  \
0          None                  None                           None
1          None                  None                           None
2          None                  None                           None
3          None                  None                           None
4          None                  None                           None
5          None                  None                           None
6          None                  None                           None
7          None                  None                           None
8          None                  None                           None
9          None                  None                           None
10         None                  None                           None
11         None                  None                           None
12         None                  None                           None
13         None                  None                           None
14         None                  None                           None
15         None                  None                           None
16         None                  None                           None
17         None                  None                           None
18         None                  None                           None
19         None                  None                           None
20         None                  None                           None
21         None                  None                           None
22         None                  None                           None
23         None                  None                           None
24         None                  None                           None
25         None                  None                           None
26         None                  None                           None
27         None                  None                           None
28         None                  None                           None
29         None                  None                           None
30         None                  None                           None
31         None                  None                           None
32         None                  None                           None
33         None                  None                           None
34         None                  None                           None
35         None                  None                           None
36         None                  None                           None
37         None                  None                           None
38         None                  None                           None
39         None                  None                           None
40         None                  None                           None
41         None                  None                           None
42         None                  None                           None
43         None                  None                           None
44         None                  None                           None
45         None                  None                           None
46         None                  None                           None
47         None                  None                           None
48         None                  None                           None
49         None                  None                           None
50         None                  None                           None
51         None                  None                           None
52         None                  None                           None
53         None                  None                           None

   meteo_nebulosite_Libelle_Long meteo_temperature meteo_force_vent  \
0                           None              None             None
1                           None              None             None
2                           None              None             None
3                           None              None             None
4                           None              None             None
5                           None              None             None
6                           None              None             None
7                           None              None             None
8                           None              None             None
9                           None              None             None
10                          None              None             None
11                          None              None             None
12                          None              None             None
13                          None              None             None
14                          None              None             None
15                          None              None             None
16                          None              None             None
17                          None              None             None
18                          None              None             None
19                          None              None             None
20                          None              None             None
21                          None              None             None
22                          None              None             None
23                          None              None             None
24                          None              None             None
25                          None              None             None
26                          None              None             None
27                          None              None             None
28                          None              None             None
29                          None              None             None
30                          None              None             None
31                          None              None             None
32                          None              None             None
33                          None              None             None
34                          None              None             None
35                          None              None             None
36                          None              None             None
37                          None              None             None
38                          None              None             None
39                          None              None             None
40                          None              None             None
41                          None              None             None
42                          None              None             None
43                          None              None             None
44                          None              None             None
45                          None              None             None
46                          None              None             None
47                          None              None             None
48                          None              None             None
49                          None              None             None
50                          None              None             None
51                          None              None             None
52                          None              None             None
53                          None              None             None

   meteo_direction_vent
0                  None

In [4]:
df_courses

,id_course,id_reunion,libelle,libelle_court,heure_depart,parcours,distance,distance_unit,corde,discipline,...,deuxieme,montant_offert_2eme,troisieme,montant_offert_3eme,quatrieme,montant_offert_4eme,cinquieme,montant_offert_5eme,incidents_type,incidents_participants
0,1,1,PRIX DU CHESNAY,DU CHESNAY,13:50:00,,2850,METRE,CORDE_GAUCHE,ATTELE,...,5,20000,15,10400,3,4800,11,2400,DISQUALIFIE_POUR_ALLURE_IRREGULIERE,"2, 6, 7, 10"
1,2,1,PRIX DE CHALLANS,DE CHALLANS,14:22:00,,2700,METRE,CORDE_GAUCHE,ATTELE,...,9,10000,6,5200,8,2400,1,1200,DISQUALIFIE_POUR_ALLURE_IRREGULIERE,10
2,3,1,PRIX DE LENS,DE LENS,14:50:00,,2700,METRE,CORDE_GAUCHE,MONTE,...,2,15000,3,7800,7,3600,10,1800,DISQUALIFIE_POUR_ALLURE_IRREGULIERE,"1, 6, 8, 9"
3,4,1,PRIX DE CARHAIX,DE CARHAIX,15:20:00,,2175,METRE,CORDE_GAUCHE,ATTELE,...,6,8250,8,4290,5,1980,2,990,DISQUALIFIE_POUR_ALLURE_IRREGULIERE,"1, 3, 7"
4,5,1,PRIX DE CERISY,DE CERISY,15:55:00,,2700,METRE,CORDE_GAUCHE,MONTE,...,2,11500,11,5980,1,2760,5,1380,DISQUALIFIE_POUR_ALLURE_IRREGULIERE,"4, 9, 12"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
349,350,54,PRIX DU ROMARIN,DU ROMARIN,20:20:00,,2700,METRE,CORDE_DROITE,MONTE,...,7,4250,10,2210,13,1020,3,510,NON_PARTANT | DISQUALIFIE_POUR_ALLURE_IRREGULIERE,"8 | 2, 6, 9"
350,351,54,PRIX DES PINS,DES PINS,20:50:00,,2050,METRE,CORDE_DROITE,ATTELE,...,8,3250,2,1690,1,780,7,390,DISQUALIFIE_POUR_ALLURE_IRREGULIERE,12
351,352,54,PRIX DES ERABLES,DES ERABLES,21:25:00,,2050,METRE,CORDE_DROITE,ATTELE,...,9,3250,11,1690,5,780,12,390,DISQUALIFIE_POUR_ALLURE_IRREGULIERE,2
352,353,54,PRIX DES CHARMILLES,DES CHARMILLES,21:55:00,,2700,METRE,CORDE_DROITE,ATTELE,...,12,3500,10,1820,11,840,4,420,DISQUALIFIE_POUR_ALLURE_IRREGULIERE,3
353,354,54,PRIX DES BOULEAUX,DES BOULEAUX,22:25:00,,2700,METRE,CORDE_DROITE,ATTELE,...,16,4250,7,2210,3,1020,15,510,NON_PARTANT | DISQUALIFIE_POUR_ALLURE_IRREGULIERE,"2 | 4, 5, 6, 8, 9, 11, 14"

In [5]:
df_participations

,id_participation,id_course,nom,numero_cheval,age,sexe,race,statut,proprietaire,entraineur,...,ordre_arrivee,jument_pleine,engagement,supplement,handicap_distance,poids_condition_monte_change,temps_obtenu,temps_obtenu_en_minute,reduction_kilometrique,allure
0,1,1,RODGERS,1,8,HONGRES,TROTTEUR FRANCAIS,PARTANT,Ecurie PELHEM,M. IZAAC,...,9,False,False,0,2850,False,213700,3m 33s,710000,TROT
1,2,1,RAVANELLO,2,8,HONGRES,TROTTEUR FRANCAIS,PARTANT,CH. NEIRINCK,V. MARTENS,...,None,False,False,0,2850,False,None,0m 0s,None,TROT
2,3,1,SERGENT DU RIB,3,7,HONGRES,TROTTEUR FRANCAIS,PARTANT,Ecurie RIB,J.L.CL. DERSOIR,...,4,False,False,0,2850,False,213110,3m 33s,708000,TROT
3,4,1,SEGUINEL MABON,4,7,MALES,TROTTEUR FRANCAIS,PARTANT,Y. DREUX,Y. DREUX,...,1,False,False,0,2850,False,211830,3m 31s,703000,TROT
4,5,1,SILVER DES PRES,5,7,HONGRES,TROTTEUR FRANCAIS,PARTANT,B. HELIAS,F. SOULOY,...,2,False,False,0,2850,False,212470,3m 32s,706000,TROT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4599,4600,354,TITAN DE LA PIERRE,12,6,HONGRES,TROTTEUR FRANCAIS,PARTANT,Mlle M. GOBET,G. RAFFESTIN,...,1,False,False,0,2725,False,211680,3m 31s,737000,TROT
4600,4601,354,TOPAZE DES ONDES,13,6,FEMELLES,TROTTEUR FRANCAIS,PARTANT,A. LANDAIS,L. LAMAZIERE,...,8,False,False,0,2725,False,215230,3m 35s,750000,TROT
4601,4602,354,TOP MARCEAUX,14,6,HONGRES,TROTTEUR FRANCAIS,PARTANT,J. BRUN,G. LAURENT,...,None,False,False,0,2725,False,None,0m 0s,None,TROT
4602,4603,354,TAMACHO MAG,15,6,HONGRES,TROTTEUR FRANCAIS,PARTANT,M. AGOSTINI,P. CALLIER,...,5,False,False,0,2725,False,213280,3m 33s,743000,TROT
4603,4604,354,TAM TAM DE GUEZ,16,6,HONGRES,TROTTEUR FRANCAIS,PARTANT,Ecurie J.PH. DUCHER,J.PH. DUCHER,...,2,False,False,0,2725,False,211700,3m 31s,737000,TROT